### ISSUE TITLE
Error When Enabling the Addon on Blender 2.91

### ISSUE THREAD

**Issue by filibis** [Nicolas-Constanty/AutoRemesher-Blender#4]
Hi, 
I just wanted to test on Blender 2.91.0 (Windos 10 - 64bit) but had this error when enabling the addon at preferences:

> Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.91\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\mesh_autoremesher\__init__.py", line 3, in <module>
    from .src.autoremesherui import AutoRemesherSettings, OBJECT_OT_autoremesher, MAINPANEL_PT_autoremesher
  File "C:\Users\filibis\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\mesh_autoremesher\src\autoremesherui.py", line 2, in <module>
    from .autoremesher import generate_quad_mesh
ImportError: DLL load failed: %1 ge├ğerli bir Win32 uygulamas─▒ de─şil.

I believe last sentence trying to say "DLL Load failed: It's not a valid Win32 file."
I hope it'll be useful for debugging. Cheers!

**Comment by toruki13** [comment]
It happens on 2.92 beta too, 

Traceback (most recent call last):
  File "C:\Users\roger\Downloads\blender-2.92.0-5d215d522541-windows64\blender-2.92.0-5d215d522541-windows64\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\roger\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mesh_autoremesher\__init__.py", line 3, in <module>
    from .src.autoremesherui import AutoRemesherSettings, OBJECT_OT_autoremesher, MAINPANEL_PT_autoremesher
  File "C:\Users\roger\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\mesh_autoremesher\src\autoremesherui.py", line 2, in <module>
    from .autoremesher import generate_quad_mesh
ImportError: DLL load failed: The specified module could not be found.

Maybe we are following wrong installation steps

**Comment by Nicolas-Constanty** [comment]
Hi @filibis and @toruki13 , thank you for your feedbacks.

These kind of issues are pretty generics, usually it's related to :
- missing symbol in the DLL
- the python version running the script is differente than the one that I used to build the Addon.

@filibis 
I think that might be the first option, I tested the Addon with Blender 2.91 installed via Steam. I'm sure that this version of Blender is compiled with x64 also. Can you tell me which installer did you use (Steam, Blender.org, Microsoft Store, ...)?
So I could debug it more easily. Maybe your version is built with x86, I this case all wind32 symbols might be indeed broken.

@toruki13 
Maybe this version of Blender is using another version than python3.7. If this is the case I need to build the Addon with the version your Blender is using. You can check the version in Blender here :

![image](https://user-images.githubusercontent.com/9875531/107882618-ae439780-6eea-11eb-9e2e-f2b101a8fe13.png)

**Comment by Carne5581** [comment]
Hi,
I also faced such a problem. 

> Traceback (most recent call last):
>   File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.91\scripts\modules\addon_utils.py", line 351, in enable
>     mod = __import__(module_name)
>   File "C:\Users\marsel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\mesh_autoremesher\__init__.py", line 3, in <module>
>     from .src.autoremesherui import AutoRemesherSettings, OBJECT_OT_autoremesher, MAINPANEL_PT_autoremesher
>   File "C:\Users\marsel\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\mesh_autoremesher\src\autoremesherui.py", line 2, in <module>
>     from .autoremesher import generate_quad_mesh
> ImportError: DLL load failed: The specified module could not be found.

My version of Blender: 
![1](https://user-images.githubusercontent.com/79058402/107886352-144b1180-6f21-11eb-8a88-f6e8c3dbe1f2.png)

**Comment by filibis** [comment]
@Nicolas-Constanty I always download from https://www.blender.org/download/ and I believe it's a ".msi" file that I launch to install.

**Comment by Nicolas-Constanty** [comment]
Hi @filibis, 
I noticed that zlib was installed in my path thanks to Inkscape and Blender was using zlib.dll of Inkscape to load the addon. 
I was able to reproduce your issue by removing Inkscape from my path, this version fixed the issue for me, can you test it?
Edit: @Carne5581 that might work for you as well

[mesh_autoremesher.zip](https://github.com/Nicolas-Constanty/AutoRemesher-Blender/files/5980435/mesh_autoremesher.zip)

**Comment by Carne5581** [comment]
Ok, the installation was successful, but an error occurred while generating the mesh: 

![image](https://user-images.githubusercontent.com/79058402/107920808-5ca11880-6f8f-11eb-9dc9-bfbe7bb86196.png)

**Comment by Nicolas-Constanty** [comment]
Thanks for helping me to improve the addon @Carne5581, I forgot to remove logs for release build. This version should be ok. 

Edit : You will need to remove it first, since the installation work this time. When you remove it the first time you might have an error, if this is the case close blender and redo it again, it should work this time (I'm working to fix this).
![image](https://user-images.githubusercontent.com/9875531/107926422-fb208000-6f75-11eb-83b3-af4b4877669c.png)

[mesh_autoremesher.zip](https://github.com/Nicolas-Constanty/AutoRemesher-Blender/files/5980435/mesh_autoremesher.zip)

**Comment by Carne5581** [comment]
I am glad to help,
Mesh creation was successful,
and share the result: 

![Autoretopology](https://user-images.githubusercontent.com/79058402/107932301-37b4a180-6f9f-11eb-823b-dd6de5abe3c4.png)

**Comment by filibis** [comment]
Hey @Nicolas-Constanty , I tested the latest zip you sent here but got the same error.

**Comment by Nicolas-Constanty** [comment]
Hi @filibis, I added some dlls from the Visual Studio redistribution in the package. They are installed in my system32 directory so I thought everyone had these DLLs too, but maybe not after all.
You can try with this one :

[mesh_autoremesher.zip](https://github.com/Nicolas-Constanty/AutoRemesher-Blender/files/5997016/mesh_autoremesher.zip)

**Comment by filibis** [comment]
Thanks @Nicolas-Constanty , this one worked out fine, I could enabled the addon. However when I tested on a simple cube, Blender crashes. I then tested on a slightly sculpted rock and it remeshed okay. Simple cube might be an edge case maybe?
Also even 0 density looks quite dense in my opinion. Isn't there an option to decrease it further?

**Comment by Nicolas-Constanty** [comment]
Hi @filibis, cool news 👍 
This package is a Blender implementation of [this tool](https://github.com/huxingyi/autoremesher), I haven't change the underlying logic of it. So, in short this solution does not work well for lowpoly meshes. I implemented this because I find out that it was a good  tool for [photogrammetry](https://www.google.com/search?q=photogrammetry&sxsrf=ALeKk00vtBr3Hz2NWAEfXaJ_KeCQWWRY7w:1613689418339&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiE8LrExfTuAhVN1hoKHQ6iBfIQ_AUoAXoECAgQAw&cshid=1613689435265224&biw=1278&bih=1283) meshes (which are usally high density meshes but have lousy topology).
The [author](https://github.com/huxingyi/autoremesher/issues) of the original tool is aware of this issue with lowpoly and is apparently working on a new version to fix this kind of issues. If a new version of the original tool is released in open source, I will probaly try to implement it for Blender.

> Also even 0 density looks quite dense in my opinion. Isn't there an option to decrease it further?

I agree with you, but unfortunately, I can easily increase the value above one, but as far as I understood from my first reading this is not the case if I want to go below zero. I won't be working on this project for at least 4-5 days, but I'll take a second look after, just in case I missed something.

Thanks for your help @filibis :smiley:.

**Comment by caseybasichis** [comment]
Hi, I'm also getting a dll error on windows on Blender 3 and 2.91.  I tested the release version as well as the one in this thread.
```
Traceback (most recent call last):
  File "C:\Program Files\blender-3.0.0-alpha+master.118803893e65-windows.amd64-release\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\casey\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mesh_autoremesher\__init__.py", line 3, in <module>
    from .src.autoremesherui import AutoRemesherSettings, OBJECT_OT_autoremesher, MAINPANEL_PT_autoremesher
  File "C:\Users\casey\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\mesh_autoremesher\src\autoremesherui.py", line 2, in <module>
    from .autoremesher import generate_quad_mesh
ImportError: DLL load failed while importing autoremesher: The specified procedure could not be found.

```

**Comment by diramazioni** [comment]
The linux version has the exact same issue and can't be enabled. I've tested it with blender 3.3.1, it seems a path issue using the dot notation `from .autoremesher import `
