### ISSUE TITLE
Linux missing symbols

### ISSUE THREAD

**Issue by Nicolas-Constanty** [Nicolas-Constanty/AutoRemesher-Blender#9]
Reported by pafurijaz on BlenderArtist.org

The 1.0.0-beta.3 on my Linux distro doesn’t works I get these errors

```
Traceback (most recent call last):
  File "/home/paf/Software/Blender-2.92.0/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/paf/.config/blender/2.92/scripts/addons/mesh_autoremesher/__init__.py", line 3, in <module>
    from .src.autoremesherui import AutoRemesherSettings, OBJECT_OT_autoremesher, MAINPANEL_PT_autoremesher
  File "/home/paf/.config/blender/2.92/scripts/addons/mesh_autoremesher/src/autoremesherui.py", line 2, in <module>
    from .autoremesher import generate_quad_mesh
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/paf/.config/blender/2.92/scripts/addons/mesh_autoremesher/src/autoremesher.cpython-37m-x86_64-linux-gnu.so)

```

I have multiple Python installations and the latest is Python 3.7

Original post : https://blenderartists.org/t/autoremesher-open-source-auto-retopology-tool/1245131/183?u=babiole

**Comment by Snudl** [comment]
When I try to enable it in the Add-ons list, mine reads:
```
Traceback (most recent call last):
  File "/usr/share/blender/2.92/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/snu/.config/blender/2.92/scripts/addons/mesh_autoremesher/__init__.py", line 3, in <module>
    from .src.autoremesherui import AutoRemesherSettings, OBJECT_OT_autoremesher, MAINPANEL_PT_autoremesher
  ImportError: attempted relative import with no known parent package
```
If that makes any difference. My system is currently on Python 3.9.2.
